In [1]:
import numpy as np

array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)
array2 = np.array([[1,2,3],[4,5,6]])
print(type(array2))
print(array2.shape)
array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [5]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [7]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [8]:
array_float = np.array([1.1,2.1,3.1])
array_int = array_float.astype('int32')
print(array_int)
#float 타입의 ndarray를 int 타입의 ndarray로 변경 -> 메모리 공간 차지 감소 가능

[1 2 3]


In [9]:
sequence_array = np.arange(10)
print(sequence_array.dtype, sequence_array.shape)

int32 (10,)


In [11]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array, zero_array.dtype, zero_array.shape)
ones_array = np.ones((3,2))
print(ones_array,ones_array.dtype, ones_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [17]:
array1 = np.arange(8)
array1_3d = array1.reshape((2,2,2))
print(array1_3d.tolist())
array1_2d = array1_3d.reshape(-1,1)
print(array1_2d.tolist(), array1_2d.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


In [21]:
array1d = np.arange(1,10)
array1d_2d = array1d.reshape(3,3)
print(array1d_2d)
print(array1d_2d[0,0])
print(array1d_2d[0,1])
print(array1d_2d[1,0])
print(array1d_2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [22]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0:2,0:2])
print(array2d[1:3,0:3])
print(array2d[1:3,:])
print(array2d[:,:])
print(array2d[0:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [23]:
print(array2d[0])
print(array2d[1])
print(array2d[0].shape, array2d[1].shape)

[1 2 3]
[4 5 6]
(3,) (3,)


In [24]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[0,1],0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [25]:
name_array = np.array(['1','2','3','4','5'])
score_array = np.array([78, 95,84,98,88])

sort_indices_acs = np.argsort(score_array)
print(sort_indices_acs)
print(name_array[sort_indices_acs])

[0 2 4 1 3]
['1' '3' '5' '2' '4']


In [27]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

dot_matrix = np.dot(A,B)
print(dot_matrix)

[[22 28]
 [49 64]]


In [29]:
A = np.array([[1,2],[3,4]])
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]
